[client]
server_addr = "云服务器ip地址"
server_port = 7001
token = "自己设定即可，需要在软件中输入这里的秘钥"
name = "client-1"
log_level = "info"
heartbeat_interval_ms = 10000
reconnect_delay_ms = 2000

[[tunnels]]
name = "svc-ssh-10001"
local_addr = "127.0.0.1"
local_port = 22
remote_port = 10001
protocol = "tcp"
